### ISSUE TITLE
[IO-2-dev] Complex Command has not implement all methods

### ISSUE THREAD

**Issue by adrian61** [iis-powp-2020-mbgc-backup/powp_jobs2d_projects#56]
![image](https://user-images.githubusercontent.com/25104303/82560279-66692d00-9b71-11ea-958d-e99d2fc97b26.png)

It's implemented only execute method.

![image](https://user-images.githubusercontent.com/25104303/82560360-9b757f80-9b71-11ea-9f11-1dd5a236b846.png)

You can see that DriverCommand has 2 methods: execute and accept.

Now it is impossible to compile and build software.

**Comment by ashleve** [comment]
The real problem is ComplexCommand class doesn't implement ICompundCommand interface. ICompundCommand interface already has accept() implemented as default method.

**Comment by ashleve** [comment]
Also, maybe ComplexCommand should be renamed to CompoundCommand so it has the same naming convention as ICompoundCommand interface?

**Comment by ashleve** [comment]
Also, I'm not sure but should ComplexCommand be located in "manager" folder, and not next to all the other driver commands classes?

**Comment by ZB63** [comment]
> 
> 
> Also, I'm not sure but should ComplexCommand be located in "manager" folder, and not next to all the other driver commands classes?

It is located in manager.

**Comment by ashleve** [comment]
> > Also, I'm not sure but should ComplexCommand be located in "manager" folder, and not next to all the other driver commands classes?
> 
> It is located in manager.

True. My question was more like: should it be located in "manager" folder instead of next to other command implementations?
I'm actually not sure myself where should it be, I'm just asking, because I don't understand why it's in "manager" currently.

**Comment by adrian61** [comment]
Issue fixed
