### ISSUE TITLE
IO-3-dev compilation erros

### ISSUE THREAD

**Issue by MR-98** [iis-powp-2020-mbgc-backup/powp_jobs2d_projects#73]
On the newest version of code app won't start due to compilation errors in classes:
- CommandTransformation
- ImmutableComplexCommand
- DriverCommandCounterVisitorTest
- DriverCommandExecutorVisitorTest

In every case the clone() method is missing. #

**Comment by kowallus** [comment]
Fixed in https://github.com/iis-powp-2020/powp_jobs2d_projects/pull/74
